sudo: required
services:
    - docker

before_install:
    - docker build -t mottekowski/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true mottekowski/react-test npm test
after_success:
    - docker build -t mottekowski/multi-client ./client
    - docker build -t mottekowski/multi-nginx ./nginx
    - docker build -t mottekowski/multi-server ./server
    - docker build -t mottekowski/multi-worker ./worker
# Log in Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to Docker HUB
    - docker push mottekowski/multi-client
    - docker push mottekowski/multi-nginx
    - docker push mottekowski/multi-server
    - docker push mottekowski/multi-worker